In [1]:
!pip install jovian --upgrade -q

In [3]:
import jovian

In [4]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "chewziqing/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/chewziqing/numpy-array-operations


'https://jovian.ai/chewziqing/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [5]:
import numpy as np

In [6]:
# List of functions explained 
function1 = np.dot (arr, arr1)
function2 = np.matmul(arr, arr1)
function3 = np.zeros((3,2))
function4 = np.ones((2, 2, 2))
function5 = np.random.rand(5)

NameError: name 'arr' is not defined

## Function 1 - np.concatenate (arr, arr2)

Concatenate 2 arrays of same dimensions

In [7]:
# concatenate arr1 and arr2 on 1 dimension
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.concatenate((arr1, arr2), axis=1)

array([[ 1.,  2.,  5.,  6.,  7.],
       [ 3.,  4.,  8.,  9., 10.]])

Explanation about example

In [20]:
# Example 2 - working
arrA = [[1, 2],
        [3, 4]]

arrB = [[4, 5]
        [6, 7]]
np.concatenate( (arr1, arr2), axis=1)

<>:5: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:5: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
/tmp/ipykernel_39/2352931978.py:5: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  arrB = [[4, 5]


TypeError: list indices must be integers or slices, not tuple

Explanation about example

In [21]:
# arr1 only has 2 elements but arr2 has 3 elements
# arr1 and arr2 have diff dimensions
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.concatenate((arr1, arr2), axis=0)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

- arr1 only has 2 elements but arr2 has 3 elements
- arr1 and arr2 have diff dimensions
-  can try reshape until 2 arrays are the same dimension

-  only use np.concatenate() when 2 arrays have the same dimension

In [22]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "chewziqing/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/chewziqing/numpy-array-operations


'https://jovian.ai/chewziqing/numpy-array-operations'

## Function 2 - np.dot(arr, arr2)

Perform dot product on two arrays

In [24]:
# Example 1 - working
arrA = np.array([[2, 3], [4, 5]])
arrB = np.array([[1, 2], [3, 4]])
np.dot(arrA, arrB)

array([[11, 16],
       [19, 28]])

Explanation about example

In [30]:
# Example 2 - working
arrA = np.array([[1, 2], [2]], dtype=object)
arrB = np.array([[3, 4], [5, 6]])
np.dot(arrA, arrB)

array([list([1, 2, 1, 2, 1, 2, 2, 2, 2, 2, 2]),
       list([1, 2, 1, 2, 1, 2, 1, 2, 2, 2, 2, 2, 2, 2])], dtype=object)

Explanation about example

In [31]:
# Example 3 - breaking (to illustrate when it breaks)
arrA = np.array([[1, 2], [2]], dtype=object)
arrB = np.array([[5, 6]])
np.dot(arrA, arrB)

ValueError: shapes (2,) and (1,2) not aligned: 2 (dim 0) != 1 (dim 0)

- If both a and b are 1-D arrays, it is inner product of vectors (without complex conjugation).

- If both a and b are 2-D arrays, it is matrix multiplication, but using matmul or a @ b is preferred.

- If either a or b is 0-D (scalar), it is equivalent to multiply and using numpy.multiply(a, b) or a * b is preferred.

- If a is an N-D array and b is a 1-D array, it is a sum product over the last axis of a and b.

- If a is an N-D array and b is an M-D array (where M>=2), it is a sum product over the last axis of a and the second-to-last axis of b:

In [33]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "chewziqing/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/chewziqing/numpy-array-operations


'https://jovian.ai/chewziqing/numpy-array-operations'

## Function 3 - arr.reshape(newShape)

Reshape array into targetted shape,  such that multiplication of new shape must be multiplication of old shape

In [36]:
# Example 1 - working
arr = np.array([[2, 4], [5, 6]])
arr.reshape(1, 4)

array([[2, 4, 5, 6]])

Explanation about example

In [38]:
# Example 2 - working
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr.reshape(-1, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

Explanation about example

In [39]:
# Example 3 - breaking (to illustrate when it breaks)
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr.reshape(3, 3)

ValueError: cannot reshape array of size 6 into shape (3,3)

- Original shape is (2, 3). New shape can only either be (3, 2), (1, 6) or (6, 1)

- Make sure the multiplication of new shape = multiplication of old shape

In [40]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "chewziqing/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/chewziqing/numpy-array-operations


'https://jovian.ai/chewziqing/numpy-array-operations'

## Function 4 - np.arange(start, end, step)

Fill in values into array

In [41]:
# Example 1 - working
np.arange(1, 100, 8)

array([ 1,  9, 17, 25, 33, 41, 49, 57, 65, 73, 81, 89, 97])

Explanation about example

In [46]:
# Example 2 - working
np.arange(4, 1, 3)

array([], dtype=int64)

Explanation about example

In [45]:
# Example 3 - breaking (to illustrate when it breaks)
np.arange(4, 1, 0)

ZeroDivisionError: division by zero

- Division by zero
- Step is zero

- Avoid using 0 or any decimal fraction when using np.arange()

In [47]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "chewziqing/numpy-array-operations" on https://jovian.ai
[jovian] Committed successfully! https://jovian.ai/chewziqing/numpy-array-operations


'https://jovian.ai/chewziqing/numpy-array-operations'

## Function 5 - np.linspace(start, end, numOfValuesBetween)

Add the specified number of values into array, starting from start to end (both inclusively)

In [48]:
# Example 1 - working
np.linspace(0, 5, 9)

array([0.   , 0.625, 1.25 , 1.875, 2.5  , 3.125, 3.75 , 4.375, 5.   ])

Explanation about example

In [49]:
# Example 2 - working
np.linspace(8, 2, 10)

array([8.        , 7.33333333, 6.66666667, 6.        , 5.33333333,
       4.66666667, 4.        , 3.33333333, 2.66666667, 2.        ])

Explanation about example

In [52]:
# Example 3 - breaking (to illustrate when it breaks)
np.linspace(8,2,-3)

ValueError: Number of samples, -3, must be non-negative.

- The given number of values to be added is negative

- Avoid using non-positive integer / non-integer as number of values in argument

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>